"""Turn a LangGraph run into the chat events the frontend renders, and frame them as SSE."""

import json
import logging
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import Any, Literal

import openai
from langchain_core.messages import AIMessage, AIMessageChunk, HumanMessage
from langchain_core.runnables import RunnableConfig
from langgraph.graph.state import CompiledStateGraph

from itinerary_planner.graph import PLANNER_NODE, REQUEST_DETAILS_NODE
from itinerary_planner.tools import RESEARCH_TOOL_NAME, YOUTUBE_TOOL_NAME

logger = logging.getLogger(__name__)

ChatEventName = Literal["token", "status", "error", "done"]


@dataclass(frozen=True)
class ChatEvent:
    name: ChatEventName
    data: dict[str, Any] = field(default_factory=dict)

    def to_sse(self) -> str:
        return f"event: {self.name}\ndata: {json.dumps(self.data)}\n\n"


def token(text: str) -> ChatEvent:
    return ChatEvent("token", {"text": text})


def status(message: str) -> ChatEvent:
    return ChatEvent("status", {"message": message})


def describe_tool_call(tool_call: dict[str, Any]) -> str:
    """A friendly, user-facing description of what a tool call is doing."""
    args = tool_call.get("args", {})
    if tool_call["name"] == YOUTUBE_TOOL_NAME:
        return "Watching the YouTube video…"
    if tool_call["name"] == RESEARCH_TOOL_NAME:
        return f"Researching {args.get('destination', 'your destination')} on the web…"
    return f"Running {tool_call['name']}…"


def describe_error(error: Exception) -> str:
    """A short message that is safe to show the user; details stay in the server log."""
    if isinstance(error, openai.RateLimitError):
        if "insufficient_quota" in str(error):
            return "The OpenAI account has run out of credits (insufficient_quota). Add credits and try again."
        return "OpenAI is rate limiting requests. Please wait a moment and try again."
    if isinstance(error, openai.AuthenticationError):
        return "The OpenAI API key was rejected. Check OPENAI_API_KEY on the server."
    return "Something went wrong while planning your trip. Please try again."


def events_from_messages(payload: tuple[Any, dict[str, Any]]) -> list[ChatEvent]:
    """Stream only the planner's visible text: skip extraction JSON, tool-internal LLM calls
    and tool-call argument chunks."""
    chunk, metadata = payload
    if metadata.get("langgraph_node") != PLANNER_NODE or not isinstance(chunk, AIMessageChunk):
        return []
    return [token(chunk.text)] if chunk.text else []


def events_from_updates(payload: dict[str, Any]) -> list[ChatEvent]:
    events: list[ChatEvent] = []
    for node_name, update in payload.items():
        messages = (update or {}).get("messages", []) if isinstance(update, dict) else []
        for message in messages:
            if not isinstance(message, AIMessage):
                continue
            if node_name == REQUEST_DETAILS_NODE:
                # Deterministic, not generated by an LLM — nothing to stream token by token.
                events.append(token(message.text))
            elif node_name == PLANNER_NODE:
                events.extend(status(describe_tool_call(call)) for call in message.tool_calls)
    return events


async def stream_reply(
    graph: CompiledStateGraph, thread_id: str, message: str
) -> AsyncIterator[ChatEvent]:
    """Run one conversational turn and yield chat events, always ending with `done`."""
    config: RunnableConfig = {"configurable": {"thread_id": thread_id}}
    graph_input = {"messages": [HumanMessage(message)]}
    try:
        async for mode, payload in graph.astream(
            graph_input, config, stream_mode=["messages", "updates"]
        ):
            events = events_from_messages(payload) if mode == "messages" else events_from_updates(payload)
            for event in events:
                yield event
    except Exception as error:  # noqa: BLE001 — reported to the client, logged with traceback
        logger.exception("Graph run failed for thread %s", thread_id)
        yield ChatEvent("error", {"message": describe_error(error)})
    yield ChatEvent("done")
